def fun(a,b):
    try:
        return a/b
        print(fun(10,5))
    except:
        print("there is an error")

